LevelData = {

    times = {3600,3600,3600,3600,3600,3600,1800,2100,1800},
    spawn_range = {{120,180},
                   {60,60},
                   {60,120},
                   {30,30},
                   {60,60},
                   {60,60},
                   {30,30},
                   {60,60},
                   {60,90}},
    enemies = {{"BasicEnemy"},
               {"BasicEnemy"},
               {"BasicEnemy", "FastEnemy"},
               {"FastEnemy"},
               {"BasicEnemy", "FastEnemy","EggEnemy"},
               {"BasicEnemy", "FastEnemy","EggEnemy","KamikazeEnemy"},
               {"BasicEnemy", "FastEnemy","KamikazeEnemy","BossEnemy"},
               {"KamikazeEnemy"},
               {"BasicEnemy", "FastEnemy","EggEnemy","KamikazeEnemy","BossEnemy"}},
    frequencies = {{1},
                   {1},
                   {3,2},
                   {1},
                   {57,38,7},
                   {14,10,2,3},
                   {1,1,0.2,0},
                   {1},
                   {14,10,3,1.5,0}},
    first_appearances = {{0},
                         {0},
                         {0,0},
                         {0},
                         {0,0,1800},
                         {0,0,0,0},
                         {0,0,0,0},
                         {0},
                         {0,0,0,0,0}},
    confirmed_appearances = {{{}},
                             {{}},
                             {{},{}},
                             {{}},
                             {{},{},{1800,2700,3600}},
                             {{},{},{},{1800}},
                             {{},{},{},{1800}},
                             {{}},
                             {{},{},{},{},{1800}}},

}